on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: 273011490881.dkr.ecr.eu-west-1.amazonaws.com/chip-m8:$(date +%s)
      AWS_ACCESS_KEY_ID: AKIAT7EGAYBA5FUPQZC2
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: docker build . --tag $TAG

      - name: Push
        run: docker push $TAG
